# Project-wide Gradle settings.

# Enables AndroidX support
android.useAndroidX=true

# Enables namespaced R classes so that each library's R class only includes its own resources
android.nonTransitiveRClass=true

# Gradle daemon JVM arguments for smooth build performance
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Kotlin code style
kotlin.code.style=official
